ARG sourceimage=tradingorg/trading
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-tradingai.txt /trading/

RUN pip install -r requirements-tradingai.txt --user --no-cache-dir
