ARG sourceimage=bot-app/trading
ARG sourcetag=develop_tradingai
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-tradingai.txt requirements-tradingai-rl.txt /trading/

RUN pip install -r requirements-tradingai-rl.txt --user --no-cache-dir
