---
version: '3'
services:
  trading:
    image: bot-app/trading:stable_tradingaitorch
    # # Enable GPU Image and GPU Resources
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: trading
    volumes:
      - "./user_data:/trading/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://bot-app.github.io/trading/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /trading/user_data/logs/trading.log
      --db-url sqlite:////trading/user_data/tradesv3.sqlite
      --config /trading/user_data/config.json
      --tradingaimodel XGBoostRegressor
      --strategy FreqaiExampleStrategy
