ARG sourceimage=tradingorg/trading
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt /trading/

RUN pip install -r requirements-freqai.txt --user --no-cache-dir
